### ISSUE TITLE
Social Media Cards

### ISSUE THREAD

**Issue by rawkode** [RawkodeAcademy/RawkodeAcademy#108]

**Comment by rawkode** [comment]
- https://github.com/delucis/astro-og-canvas#readme
- https://github.com/shepherdjerred/astro-opengraph-images

**Comment by icepuma** [comment]
Both plugins fail due to an incompatibility regarding SSR:

* https://github.com/delucis/astro-og-canvas#readme
```shell
01:12:20 [ERROR] [vite] x Build failed in 159ms
[commonjs--resolver] [plugin vite:resolve] Cannot bundle Node.js built-in "node:fs/promises" imported from "node_modules/astro-og-canvas/dist/generateOpenGraphImage.js". Consider disabling ssr.noExternal or remove
 the built-in dependency.
```

* https://github.com/shepherdjerred/astro-opengraph-images
```shell
24:58:49 [ERROR] [vite] x Build failed in 1.23s
[commonjs--resolver] [plugin vite:resolve] Cannot bundle Node.js built-in "fs" imported from "node_modules/astro-opengraph-images/dist/util.js". Consider disabling ssr.noExternal or remove the built-in dependency.
```

Searching for a fix / alternative later :)

**Comment by icepuma** [comment]
I will try to contribute the `static` render capable og images

**Comment by rawkode** [comment]
This can now be solved rather trivially by using the new image-service.

PR should include OpenGraph tags that reference a dynamic URL.

This will required #187 to be closed first.
