### ISSUE TITLE
Community Discourse

### ISSUE THREAD

**Issue by rawkode** [RawkodeAcademy/RawkodeAcademy#122]
Over the years, we've discussed and deliberated on the best approach for providing a way for community members to engage with one another.

Currently, Discord is the status quo. However, we did enable GitHub Discussions a while back and Matrix, along with others, have been suggested to adopt a more open source platform.

The Discord server provides real-time chat for anyone that wants to be involved, but is rather lacking in asynchronous features, such as a forum.

Do we need async? I believe so, this would enable people to request help with problems that stand more chance of getting a response, jobs forums, sharing demo videos for show and tell; and much more.

However, I do believe we continue to need real time too.

Let us know what you would prefer and what you want from the community and this will allow us to craft a CDR to improve the status quo.

**Comment by icepuma** [comment]
I totally agree, that we're missing the `async` part in the community. I imagine having a forum like in the old days, which also helps in "timezone independent communication". Two tools I think would be worth a try:
* https://www.discourse.org/ - "battleproofen" and well known
* https://flarum.org/ - we would have to try it out

**Comment by mocdaniel** [comment]
While I agree that an 'async by default' channel (aka forum) might be needed/wanted, I would like to keep Discord along with it.

Subjectively, Discord works in both, sync/async ways for me, and while I get that this isn't the case for everyone, I value the (rare) real-time chats on Discord most about the community.

**Comment by icepuma** [comment]
I would keep Discord, but drop all channels except
* the text channel `#general`
* the voice channel `#coffee-bar`

When people need ad-hoc help, they can create a forum post and link it in `#general` or we use a thread in Discord to discuss things in detail.

**Comment by mocdaniel** [comment]
We could probably get an integration between forum <-> Discord up and running which posts those links automagically, right? That'd be a neat solution, imo.

**Comment by rawkode** [comment]
Closing as per #127
