### ISSUE TITLE
IaC for Discord

### ISSUE THREAD

**Issue by rawkode** [RawkodeAcademy/RawkodeAcademy#128]
* [ ] Roles
* [ ] Categories
* [ ] Channels
* [ ] Events

**Comment by rawkode** [comment]
Events are currently blocked by lack of API for Terraform.

Everything else should be OK.

**Comment by icepuma** [comment]
https://github.com/discord/discord-api-docs/pull/7058

**Comment by rawkode** [comment]
Reference code for this:

- ./infrastructure/cloud.rawkode.tfstate/infrastructure
- ./infrastructure/dns/
- ./infrastructure/kubernetes-platform/
- ./infrastructure/gitlab/
- ./presentations/lets-meet-cdktf-python

**Comment by rawkode** [comment]
You will need Discord OAuth access, ping me on Discord for access.

**Comment by rawkode** [comment]
No longer required, as Zulip is taking over.
