### ISSUE TITLE
Static Pages: HTML/CSS Development:

### ISSUE THREAD

**Issue by hassantariq1122** [RawkodeAcademy/RawkodeAcademy#157]
- Create a template for the static HTML pages.
- Convert each PDF page into an HTML page using the template.
- Ensure proper formatting and styling.

**Link to the PDF Document:**
[Rawkode Academy Partner Deck.pdf](https://github.com/user-attachments/files/16314971/Rawkode.Academy.Partner.Deck.pdf)

**Comment by rawkode** [comment]
I don't think it should be one html page per PDF page. I'd like to see the contents of the PDF captured and formatted on to a single static page.

**Comment by rawkode** [comment]
Something like this, but with more of a visual impact.

https://ndcoslo.com/become-a-partner

**Comment by rawkode** [comment]
Closed by #232
