### ISSUE TITLE
Static Pages: Website Integration

### ISSUE THREAD

**Issue by hassantariq1122** [RawkodeAcademy/RawkodeAcademy#158]
- Add navigation links to the new static pages.
- Ensure new pages are responsive and fit the existing website design.
- Test the integration to ensure all pages are correctly linked and displayed.

**Link to the PDF Document:**
[Rawkode Academy Partner Deck.pdf](https://github.com/user-attachments/files/16314971/Rawkode.Academy.Partner.Deck.pdf)

**Comment by rawkode** [comment]
Closed by #232
