### ISSUE TITLE
Website: Static Pages

### ISSUE THREAD

**Issue by hassantariq1122** [RawkodeAcademy/RawkodeAcademy#159]
**Description**
We are looking for collaborators to help us convert PDF documents into static web pages on our website. This will enhance the accessibility and user experience by allowing users to view content directly on the site without needing to download and open PDF files separately.

**What We Need:**
- #156 
- #157
- #158

**Expected Outcome:**

By the end of this task, we aim to have each page of our PDF document available as a static page on our website, ensuring a seamless and interactive user experience.

**Comment by rawkode** [comment]
I don't think we're looking for collaborators for this, as I believe your team will be picking up these tasks?
