### ISSUE TITLE
Setup RPC Astro Deployment for Trigger.dev

### ISSUE THREAD

**Issue by rawkode** [RawkodeAcademy/RawkodeAcademy#202]
This Astro site acts as a webhook receiver for any events we need to bring into the Academy platform. 

These events can trigger trigger.dev tasks, which will also be defined in this service.

The first task we want to handle is a YouTube RSS subscription and thread creation on Discord

**Comment by rawkode** [comment]
The minute I start this, I see this tweet:

https://x.com/elithrar/status/1816593557035139227?t=HTmLus8XRLJE4KKIhQdaJw&s=19

**Comment by rawkode** [comment]
OK. I've made extremely good progress in this,  but it comes with a catch. As we add more secrets, like WorkOS and now Trigger.dev; it becomes exponentially harder to welcome new contributors to these services and potentially Web.

The only way around this is to provide a staging environment and isolate the authentication to its own service.

Not a blocker right now but something I want to note as I work on cross domain integrations

**Comment by rawkode** [comment]
I also want to experiment with [Nango](https://www.nango.dev/) as a means to proxy all integrations and make local dev easier for contributors

**Comment by icepuma** [comment]
So the architecture will something like?
* Something on Discord/YouTube/... changes
* The change hits Nango
* Nango then calls our Astro app/s with the correct hook
* Our Astro app/s process the change

**Comment by rawkode** [comment]
I think it's more likely to be that all webhook from third party services hit the RPC endpoint. We may add Memphis.dev, or similar, if we need scale more than I suspect.

The RPC does what it needs via it's handlers, but if those handlers need to speak to a third party integrations with authentication - we proxy that through Nango; meaning contributors can create Discord events, as an example, without having our Discord keys

**Comment by icepuma** [comment]
Ah now I get it. Thanks for the explanation

**Comment by rawkode** [comment]
Sorry, I was working on main.

Implemented via

https://github.com/RawkodeAcademy/RawkodeAcademy/compare/fbfee6a90c7f865f1c16311977022ae933d99b83...949462b277b3dc38e34ceb2c9b70f110c5f30803
