### ISSUE TITLE
Form Templates for Defects & Enhancements

### ISSUE THREAD

**Issue by rawkode** [RawkodeAcademy/RawkodeAcademy#213]

**Comment by icepuma** [comment]
Already working on it ^^

**Comment by icepuma** [comment]
Everything despite a Defect is an Enhancement or do we want to support more things?

**Comment by rawkode** [comment]
Hmm. Open to discussion, but my initial thought is: 

- Defect (Behaviour is broken)
- Enhancement (Add new feature)
- Change (Change existing feature)
- Operations (Infra & Automation)

**Comment by icepuma** [comment]
I think I'll add some things and we can elaborate things on the PR
