### ISSUE TITLE
Sync Events to Discord

### ISSUE THREAD

**Issue by icepuma** [RawkodeAcademy/RawkodeAcademy#234]
### Check for existing issues

* [x] Completed

### Description

The Discord API has an endpoint to [get all scheduled guild events](https://discord.com/developers/docs/resources/guild-scheduled-event#list-scheduled-events-for-guild).

We should have some piece of code querying said endpoint (including `with_user_count`) and insert the scheduled events.

Discord is working on https://github.com/discord/discord-api-docs/issues/6799 to add the `recurrence_rule` to a scheduled event.

When we have this data, we can build a website for events where people can see which events are happening (even show a calendar) and make it easy to subscribe (via downloadable `.ics`) to individual events or to the series.

We either compute upcoming events (with the help of `recurrence_rule`) right before inserting them into the events service db or when displaying the page and make the data highly cacheable.

### Do you want to help us with implementing the change? (If "Yes", we assign you the ticket)

No

**Comment by rawkode** [comment]
Related #128

**Comment by randax** [comment]
I can take a look

**Comment by icepuma** [comment]
I think we have to add the `recurrence_rule` stuff to https://github.com/bwmarrin/discordgo first, to add it to https://github.com/Lucky3028/terraform-provider-discord to use it in our repos :)

**Comment by rawkode** [comment]
Support is available on Discord's TypeScript SDK 

So we can either write our own code or use Pulumi and a dynamic provider

**Comment by icepuma** [comment]
I know, but I thought we provide it to more people than just us

**Comment by rawkode** [comment]
No longer required as we're adopting Zulip
