### ISSUE TITLE
System Authentication Service

### ISSUE THREAD

**Issue by rawkode** [RawkodeAcademy/RawkodeAcademy#281]
We need the ability to authenticate system / privileged requests.

In-order for us to rollout the People service with correct RBAC, we need the ability for the system to be able to query people, and other APIs.

**Comment by rawkode** [comment]
Honestly, if we're going to do this and provide system level security - perhaps we should also roll out Better Auth and handle our own users too.

cc @icepuma

**Comment by icepuma** [comment]
When `🚧 We still in beta and we don't recommend to use better-auth in production just yet.` is okay for us, we should do it :)

**Comment by rawkode** [comment]
[Zitadel](https://zitadel.com/) does M2M/Service Accounts.
