### ISSUE TITLE
Bug: Homepage Layout on Mobile

### ISSUE THREAD

**Issue by rawkode** [RawkodeAcademy/RawkodeAcademy#40]
Tagline text seems to put things off a little

cc @allygraham

**Comment by allygraham** [comment]
@rawkode PR is in

**Comment by rawkode** [comment]
@allygraham Looks like it's a Safari / WebKit bug.

Still happens on mobile and I just checked Safari desktop - same thing.

**Comment by rawkode** [comment]
Or maybe I forgot to deploy 😓
