### ISSUE TITLE
Continuous Deployment Pipeline for Website

### ISSUE THREAD

**Issue by rawkode** [RawkodeAcademy/RawkodeAcademy#84]
Build and implement a Dagger function to automate the process of building and deploying the Rawkode Academy website to Cloudflare upon every merge to the `main` branch.

The task includes:

* Setting up a Dagger pipeline that triggers on merges to the `main` branch.
* Configuring the build process for the website within the Dagger function.
* Integrating deployment to Cloudflare as the final step in the pipeline.
* Ensuring that the entire process is automated and reliable, with appropriate error handling and notifications.

**Comment by randax** [comment]
I can take a look
